<!DOCTYPE html>
<html>
<head>
    <?= $this->meta->head($meta['head']) ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <div class="pt-4"></div>
                <h1><?= $info->title ?></h1>

                <hr>
                
                <div class="row">
                    <div class="col-md-3">
                        <?php $this->partial('profile/setting/tabs'); ?>
                    </div>
                    <form method="POST" class="col-md-4">
                        <?php if($saved): ?>
                            <div class="alert alert-success"><strong>Success!</strong> Your account is updated</div>
                        <?php endif; ?>

                        <div class="form-group">
                            <label>Public Email</label>
                            <input type="email" name="contact-email" class="form-control" required value="<?= $this->req->getPost('contact-email', $profile->contact->email ?? '') ?>">
                            <?php if($err = $form->getError('contact-email')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Public Phone</label>
                            <input type="tel" name="contact-phone" class="form-control" required value="<?= $this->req->getPost('contact-phone', $profile->contact->phone ?? '') ?>">
                            <?php if($err = $form->getError('contact-phone')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Manager Phone</label>
                            <input type="tel" name="contact-manager" class="form-control" required value="<?= $this->req->getPost('contact-manager', $profile->contact->manager ?? '') ?>">
                            <?php if($err = $form->getError('contact-manager')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Country</label>
                            <input type="text" name="addr_country" class="form-control" required value="<?= $this->req->getPost('addr_country', $profile->addr_country) ?>">
                            <?php if($err = $form->getError('addr_country')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>State</label>
                            <input type="text" name="addr_state" class="form-control" required value="<?= $this->req->getPost('addr_state', $profile->addr_state) ?>">
                            <?php if($err = $form->getError('addr_state')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>City</label>
                            <input type="text" name="addr_city" class="form-control" required value="<?= $this->req->getPost('addr_city', $profile->addr_city) ?>">
                            <?php if($err = $form->getError('addr_city')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Street</label>
                            <textarea name="addr_street" class="form-control"><?= $this->req->getPost('addr_street', $profile->addr_street) ?></textarea>
                            <?php if($err = $form->getError('addr_street')): ?>
                                <small class="form-text text-muted"><?= $err->text ?></small>
                            <?php endif; ?>
                        </div>

                        <div class="text-right">
                            <button class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <?= $this->meta->foot($meta['foot']) ?>
</body>
</html>