<!DOCTYPE html>
<html>
<head>
    <?= $this->meta->head($meta['head']) ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <div class="pt-4"></div>
                <h1><?= $info->title ?></h1>

                <hr>
                
                <div class="row">
                    <div class="col-md-3">
                        <?php $this->partial('profile/setting/tabs'); ?>
                    </div>
                    <form method="POST" id="form" class="col-md-4">
                        <?php if($saved): ?>
                            <div class="alert alert-success"><strong>Success!</strong> Your account is updated</div>
                        <?php endif; ?>

                        <input type="hidden" id="educations" name="educations" value="<?= $this->req->getPost('educations', $profile->educations ?? '[]') ?>">

                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <input type="text" id="inp-level" class="form-control" placeholder="Type">
                                </div>
                                <div class="form-group">
                                    <input type="text" id="inp-year" class="form-control" placeholder="Year">
                                </div>
                                <div class="form-group">
                                    <input type="text" id="inp-place" class="form-control" placeholder="Place">
                                </div>

                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <button class="btn btn-secondary" id="inp-add" type="button">Add</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?php
                        $profs = $this->req->getPost('educations', $profile->educations ?? '[]');
                        $profs = json_decode($profs);
                        ?>
                        <div class="list-group mt-2" id="list">
                            <?php foreach($profs as $prof): ?>
                                <a class="prof-remove list-group-item d-flex justify-content-between align-items-center list-group-item-action" href="#" title="Click to remove" data-level="<?= $prof->level ?>" data-year="<?= $prof->year ?>" data-place="<?= $prof->place ?>">
                                    <div><?= $prof->level ?> <small><?= $prof->place ?></small></div>
                                    <span class="badge badge-primary badge-pill"><?= $prof->year ?></span>
                                </a>
                            <?php endforeach; ?>
                        </div>

                        <div class="text-right mt-3">
                            <button class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <?= $this->meta->foot($meta['foot']) ?>

    <script>
        $('#form').on('submit', function(){
            let result = [];
            $('#list > a').each(function(i,e){
                let row = {
                    level: e.dataset.level,
                    year : e.dataset.year,
                    place: e.dataset.place
                }
                result.push(row)
            })

            $('#educations').val( JSON.stringify(result) )
        });

        $('#list').on('click', '.prof-remove', function(e){
            $(this).remove();
            return false;
        })

        $('#inp-add').click(function(){
            let safe = {
                level: $('#inp-level').val(),
                year : $('#inp-year').val(),
                place: $('#inp-place').val()
            }

            if(!safe.level)
                return $('#inp-type').focus();
            if(!safe.year)
                return $('#inp-year').focus();
            if(!safe.place)
                return $('#inp-place').focus();

            $('#list').append(`
                <a class="prof-remove list-group-item d-flex justify-content-between align-items-center list-group-item-action" href="#" title="Click to remove" data-level="${safe.level}" data-year="${safe.year}" data-place="${safe.place}">
                    <div>${safe.level} <small>${safe.place}</small></div>
                    <span class="badge badge-primary badge-pill">${safe.year}</span>
                </a>
            `);

            $('#inp-place').val('');
            $('#inp-year').val('');
            $('#inp-level').val('').focus();
        });
    </script>
</body>
</html>